name: Email Step Demo

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: 23f2002553@ds.study.iitm.ac.in
        run: echo "This step is named with my email."
